#!/bin/bash
#SBATCH --job-name="innerproduct"
#SBATCH --output="innerproduct.%j.%N.out"
#SBATCH --partition=shared
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --export=ALL
#SBATCH -t 01:00:00
#SBATCH -A TG-ASC160059
#This job runs with 1 node, 8 cores per node for a total of 24 cores.
#ibrun in verbose mode will give binding detail
export CILK_NWORKERS=8
cd /home/$USER/hw4
#ibrun -v ./innerproduct 1000000
ibrun -v ./bc -p -g 128 128
